#!/usr/bin/python3
def raise_exception_msg(message=""):
    print(f"{message}")
    raise NameError
